package world;

public enum Tags {
    ACCOUNTING("Бухгалтерия"),
    AIRPORT("Аэропорт"),
    AMUSEMENT_PARK("Парк развлечений"),
    AQUARIUM("Океонариум"), //аквариум
    ART_GALLERY("Галерея"),
    ATM("Банкомат"),
    BAKERY("Пекарня"),
    BANK("Банк"),
    BAR("Бар"),
    BEAUTY_SALON("Салон красоты"),
    BICYCLE_STORE("Велосипедный магазин"),
    BOOK_STORE("Книжный магазин"),
    BOWLING_ALLEY("Боулинг"),
    BUS_STATION("Остановка"),
    CAFE("Кафе"),
    CAMPGROUND("Лагерь"),
    CAR_DEALER("Автосалон"),
    CAR_RENTAL("Аренда автомобиля"),
    CAR_REPAIR("Ремонт автомобиля"),
    CAR_WASH("Автомойка"),
    CASINO("Казино"),
    CEMETERY("Крематорий"),
    CHURCH("Церковь"),
    CITY_HALL("Ратуша"),
    CLOTHING_STORE("Магазин одежды"),
    CONVENIENCE_STORE("Круглосуточный магазин"),
    COURTHOUSE("Суд"),
    DENTIST("Стоматолог"),
    DEPARTMENT_STORE("Универмаг"),
    DOCTOR("Доктор"),
//    DRUGSTORE("Аптека"),
    ELECTRICIAN("Электрика"),
    ELECTRONICS_STORE("Магазин электроники"),
    EMBASSY("Посольство"),
    FIRE_STATION("Пожарная служба"),
    FLORIST("Флорист"),
    FUNERAL_HOME("Похоронное бюро"),
    FURNITURE_STORE("Мебельный магазин"),
    GAS_STATION("Заправка"),
    GROCERY_OR_SUPERMARKET("Супермаркет"),
    GYM("Спортзал"),
    HAIR_CARE("Парикмахерская"),
    HARDWARE_STORE("Магазин техники"),
    HINDU_TEMPLE("Индуистский храм"),
    HOME_GOODS_STORE("Магазин товаров для дома"),
    HOSPITAL("Госпиталь"),
    INSURANCE_AGENCY("Страховая"),
    JEWELRY_STORE("Ювелирный магазин"),
    LAUNDRY("Прачечная"),
    LAWYER("Адвокат"),
    LIBRARY("Библиотека"),
    LIGHT_RAIL_STATION("Ж/д станция"),
    LIQUOR_STORE("Алкомаркет"),
    LOCAL_GOVERNMENT_OFFICE("Местное управление"),
    LOCKSMITH("Слесарь"),
    MEAL_DELIVERY("Доставка еды"),
    MEAL_TAKEAWAY("Выдача еды"),
    MOSQUE("Мечеть"),
    MOVIE_RENTAL("Аренда фильмов"),
    MOVIE_THEATER("Кинотеатр"),
//    MOVING_COMPANY(""),
    MUSEUM("Музей"),
    NIGHT_CLUB("Ночной клуб"),
    PAINTER("Художник"),
    PARK("Парк"),
    PARKING("Парковка"),
    PET_STORE("Зоомагазин"),
    PHARMACY("Аптека"),
//    PHYSIOTHERAPIST(""),
    PLUMBER("Сантехник"),
    POLICE("Полиция"),
    POST_OFFICE("Почта"),
    PRIMARY_SCHOOL("Начальная школа"),
    REAL_ESTATE_AGENCY("Агенство по недвижимости"),
    RESTAURANT("Ресторан"),
//    ROOFING_CONTRACTOR(""),
//    RV_PARK(""),
    SCHOOL("Школа"),
    SECONDARY_SCHOOL("Средняя школа"),
    SHOE_STORE("Магазин обуви"),
    SHOPPING_MALL("Торговый центр"),
    SPA("Спа"),
    STADIUM("Стадион"),
    STORAGE("Склад"),
    STORE("магазин"),
    SUBWAY_STATION("Станция метро"),
    SUPERMARKET("Супермаркет"),
    SYNAGOGUE("Синагога"),
    TAXI_STAND("Такси"),
//    TOURIST_ATTRACTION(" "),
    TRAIN_STATION("Ж/д станция"),
    TRANSIT_STATION("Транзитная станция"),
    TRAVEL_AGENCY("Турагенство"),
    UNIVERSITY("Университет"),
    VETERINARY_CARE("Ветклиника"),
    ZOO("Зоопарк");
    private final String tag;
    Tags(String tag) {
        this.tag = tag;
    }

    public String toString() {
        return tag;
    }
}
